ajout de l'option "status" a la commande bin/slapd permettant de connaitre l'etat du processus
git-svn-id: file:///root/pkgi/trunk@72 1d9e17c5-d814-4e76-8053-328317d3193c

diff --git a/ldap/bin/slapd b/ldap/bin/slapd
--- a/ldap/bin/slapd
+++ b/ldap/bin/slapd
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+
 # Specify path variable
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
@@ -9,7 +10,21 @@ set -e
 # Stop processing if slapd is not there
 [ -x /usr/sbin/slapd ] || exit 0
 
-
+# INIST
+if [[ -f /inist/env/inist.env.ksh ]]
+then
+  # la machine est correctement installée, tout va bien
+  . /inist/env/inist.env.ksh
+else
+  # dans le cas ou la machine ne contient pas les fichiers d'environement inist
+  # on defini en dur ceux dont on aura besoin
+  RC_OK_TERMINE=0;       # RC_LIB[0]="Sortie normale."
+  RC_ERR_PARAM=103;      # RC_LIB[103]="Erreur dans les parametres d'appel."
+  RC_ERR_YETSTARTED=240; # RC_LIB[240]="L'application tourne deja."
+  RC_ERR_NOTSTARTED=241; # RC_LIB[241]="L'application ne tourne pas."
+  RC_ERR_NOPROCESS=242;  # RC_LIB[242]="Le processus ne tourne pas."
+  RC_ERR_PROGRAM=255;    # RC_LIB[255]="Autre erreur."
+fi
 
 # Default location of the slapd.conf file
 SLAPD_CONF=<?php echo getenv('APPNAME_HOME'); ?>/etc/slapd.conf
@@ -213,11 +228,30 @@ stop() {
 	echo .
 }
 
+# Check if ldap is running
+status() {
+	if [[ ! -f ${SLAPD_PIDFILE} ]]
+	then
+                echo "OpenLDAP not started"
+		exit ${RC_ERR_NOTSTARTED}
+	fi
+	pid=`cat ${SLAPD_PIDFILE}`
+        ps -ef | cut -c 10-14,48- | grep "${pid}" | grep "<?php echo getenv('APPNAME_LDAP_PORT'); ?>" > /dev/null
+	if [[ ${?} -ne 0 ]]
+	then
+                echo "OpenLDAP process not found"
+		exit ${RC_ERR_NOPROCESS}
+	fi  
+        echo "OpenLDAP is listening on <?php echo getenv('APPNAME_LDAP_LISTEN_INTERFACE'); ?>:<?php echo getenv('APPNAME_LDAP_PORT'); ?> with pid ${pid}"
+}
+
 case "$1" in
   start)
   	start ;;
   stop)
   	stop ;;
+  status)
+  	status ;;
   restart|force-reload)
   	stop
 	start
@@ -227,3 +261,5 @@ case "$1" in
 	exit 1
 	;;
 esac
+
+exit ${RC_OK_TERMINE}
