- Retire la variable d'env APPNAME_MYSQL_ROOT_PASSWORD pour des raisons de securité - Ajoute l'option rootpassword au script bin/pkgi-mysqltools permettant de definir un mot de passe root
git-svn-id: file:///root/pkgi/trunk@155 1d9e17c5-d814-4e76-8053-328317d3193c

diff --git a/mysql/bin/pkgi-mysqltools b/mysql/bin/pkgi-mysqltools
--- a/mysql/bin/pkgi-mysqltools
+++ b/mysql/bin/pkgi-mysqltools
@@ -13,8 +13,72 @@ case ${1} in
 	;;
 
     -i | init)
-	# initialisation de la base
-	<?php echo getenv('APPNAME_HOME') ?>/usr/bin/mysql_install_db
+	# initialisation de la base avec 
+        # creation et reglage de l'utilisateur de maintenance: debian-sys-maint
+        <?php echo getenv('APPNAME_HOME') ?>/etc/init.d/mysql stop > /dev/null
+        if [ "$?" != "0" ]; then
+          echo "Database cannot be initialized because mysql server cannot be stopped..."
+          exit 1
+        fi
+	<?php echo getenv('APPNAME_HOME') ?>/usr/bin/mysql_install_db > /dev/null
+
+        # reglage du mot de passe debian-sys-maint
+	pass="`sed -n 's/^[ 	]*password *= *// p'  <?php echo getenv('APPNAME_HOME') ?>/etc/mysql/debian.cnf | sed 's/\s// p' | head -n 1`"
+	tfile=`mktemp`
+	if [ ! -f "$tfile" ]; then
+	    return 1
+	fi
+	cat << EOF > $tfile
+USE mysql;
+REPLACE INTO user SET host='localhost', user='debian-sys-maint', password=password('$pass'), Select_priv='Y', Insert_priv='Y', Update_priv='Y', Delete_priv='Y', Create_priv='Y', Drop_priv='Y', Reload_priv='Y', Shutdown_priv='Y', Process_priv='Y',  File_priv='Y', Grant_priv='Y', References_priv='Y', Index_priv='Y', Alter_priv='Y', Show_db_priv='Y', Super_priv='Y', Create_tmp_table_priv='Y', Lock_tables_priv='Y', Execute_priv='Y', Repl_slave_priv='Y', Repl_client_priv='Y';
+EOF
+	MYSQL_BOOTSTRAP="/usr/sbin/mysqld --bootstrap --datadir=<?php echo getenv('APPNAME_HOME') ?>/var/lib/mysql --skip-grant-tables --skip-bdb --skip-innodb --skip-ndbcluster"
+	$MYSQL_BOOTSTRAP <$tfile
+        if [ "$?" != "0" ]; then
+          echo "Error: debian-sys-maint cannot be created."
+          rm -f $tfile
+          exit 1
+        else
+          echo "Database has been initialized"
+          rm -f $tfile
+        fi
+	;;
+
+
+    -rp | rootpassword)
+	# initialisation du mot de passe root
+	if [[ ${#} -lt 2 ]]
+        then
+            echo "Error: missing parameter (root password)."
+            echo "Example: bin/pkgi-mysqltools rootpassword a13fz22"
+            exit 1
+        fi
+        <?php echo getenv('APPNAME_HOME') ?>/etc/init.d/mysql stop > /dev/null
+        if [ "$?" != "0" ]; then
+          echo "Root password cannot be changed because mysql server cannot be stopped..."
+          exit 1
+        fi
+        ROOT_PASSWORD=$2
+	MYSQL_BOOTSTRAP="/usr/sbin/mysqld --bootstrap --datadir=<?php echo getenv('APPNAME_HOME') ?>/var/lib/mysql --skip-grant-tables --skip-bdb --skip-innodb --skip-ndbcluster"
+	tfile=`mktemp`
+	if [ ! -f "$tfile" ]; then
+	    return 1
+	fi
+	cat << EOF > $tfile
+USE mysql;
+UPDATE user SET password=PASSWORD("$ROOT_PASSWORD") WHERE user='root';
+FLUSH PRIVILEGES;
+EOF
+	$MYSQL_BOOTSTRAP <$tfile
+        if [ "$?" != "0" ]; then
+          echo "Root password cannot be changed because mysql database has not been initialized."
+          echo "Please firstly initialize the mysql database: bin/pkgi-mysqltools init"
+          rm -f $tfile
+          exit 1
+        else
+          echo "Root password has been initialized to $ROOT_PASSWORD"
+          rm -f $tfile
+        fi
 	;;
 
     -mr | makeroot)
@@ -91,12 +155,13 @@ case ${1} in
 	echo "usage: $0 ( query | dump | init | makeroot | copyto | copyfrom )"
 	cat <<EOF
 
-   -q  | query     - Permet de lancer la commande mysql (placez vos paramètres à la suite)
-   -i  | init      - Initialisation de la base
-   -d  | dump      - Permet de lancer la commande mysqldump (placez vos parametres à la suite)
-   -mr | makeroot  - Permet de donner les droits de connexion à un hostname passé en paramètre
-   -t  | copyto    - Copie d'une ou de toutes les bases sur un autre serveur 
-   -f  | copyfrom  - Récupération d'une ou de toutes les bases venant d'un autre serveur
+   -q  | query        - Permet de lancer la commande mysql (placez vos paramètres à la suite)
+   -i  | init         - Initialisation de la base
+   -rp | rootpassword - Réglage du mot de passe root (passé en paramètre)
+   -d  | dump         - Permet de lancer la commande mysqldump (placez vos parametres à la suite)
+   -mr | makeroot     - Permet de donner les droits de connexion à un hostname passé en paramètre
+   -t  | copyto       - Copie d'une ou de toutes les bases sur un autre serveur 
+   -f  | copyfrom     - Récupération d'une ou de toutes les bases venant d'un autre serveur
 
 EOF
 
