Ajout de l'option -bc (-backup-cron) au script bin/pkgi-mysqltools permettant d'installer ou de désinstaller une saugevarde quotidienne et automatique de la base de données dans un fichier compressé.
git-svn-id: file:///root/pkgi/trunk@387 1d9e17c5-d814-4e76-8053-328317d3193c

diff --git a/mysql/bin/pkgi-mysqltools b/mysql/bin/pkgi-mysqltools
--- a/mysql/bin/pkgi-mysqltools
+++ b/mysql/bin/pkgi-mysqltools
@@ -30,20 +30,38 @@ case ${1} in
                 | grep -v "^information_schema$" \
                 | grep -v "^mysql$"`
         if [ "$APP_BASES" == "" ]; then
-            echo "Rien à dumper car aucune base de données trouvée."
+            echo "Rien à dumper car aucune base de données trouvée."  >&2
             exit 1;
         fi
         
         # dump des tables trouvées
         $APP_HOME/usr/bin/mysqldump --databases $APP_BASES $*
     ;;
+    
+    -bc | -backup-cron | backup-cron)
+        shift 1
+        if [ "$1" != "install" ]; then
+            if [ "$1" != "uninstall" ]; then
+                echo "Indiquez si vous désirez installer ou désinstaller la crontab de sauvegarde de la base mysql" >&2
+                echo "Rajoutez sur la ligne de commande 'install' ou 'uninstall'" >&2
+                exit 1
+            else
+                rm -f <?php echo getenv('APPNAME_HOME') ?>/etc/cron.d/mysql-backup
+                <?php echo getenv('APPNAME_HOME') ?>/bin/pkgi-install-crontab
+            fi
+        else
+            echo "<?php echo rand(0,59); ?> 3 * * * <?php echo getenv('APPNAME_HOME') ?>/bin/pkgi-mysqlbackup" > <?php echo getenv('APPNAME_HOME') ?>/etc/cron.d/mysql-backup
+            <?php pkgi_track_instance(getenv('APPNAME_HOME').'/etc/cron.d/mysql-backup'); ?> 
+            <?php echo getenv('APPNAME_HOME') ?>/bin/pkgi-install-crontab
+        fi
+    ;;    
 
     -i | -init | init)
         # initialisation de la base avec 
         # creation et reglage de l'utilisateur de maintenance: debian-sys-maint
         <?php echo getenv('APPNAME_HOME') ?>/etc/init.d/mysql stop > /dev/null
         if [ "$?" != "0" ]; then
-            echo "Database cannot be initialized because mysql server cannot be stopped..."
+            echo "Database cannot be initialized because mysql server cannot be stopped..." >&2
             exit 1
         fi
         <?php echo getenv('APPNAME_HOME') ?>/usr/bin/mysql_install_db > /dev/null
@@ -52,7 +70,8 @@ case ${1} in
         pass="`sed -n 's/^[ 	]*password *= *// p'  <?php echo getenv('APPNAME_HOME') ?>/etc/mysql/debian.cnf | sed 's/\s// p' | head -n 1`"
         tfile=`mktemp`
         if [ ! -f "$tfile" ]; then
-            return 1
+            echo "Erreur inattendue"  >&2
+            exit 1
         fi
         cat << EOF > $tfile
 USE mysql;
@@ -61,7 +80,7 @@ EOF
         MYSQL_BOOTSTRAP="<?php echo getenv('APPNAME_HOME') ?>/usr/sbin/mysqld --bootstrap --datadir=<?php echo getenv('APPNAME_HOME') ?>/var/lib/mysql --skip-grant-tables --skip-innodb"
         $MYSQL_BOOTSTRAP <$tfile
         if [ "$?" != "0" ]; then
-            echo "Error: debian-sys-maint cannot be created."
+            echo "Error: debian-sys-maint cannot be created." >&2
             rm -f $tfile
             exit 1
         else
@@ -81,13 +100,13 @@ EOF
     -rp | -rootpassword | rootpassword)
         # initialisation du mot de passe root
         if [ ${#} -lt 2 ]; then
-            echo "Error: missing parameter (root password)."
-            echo "Example: bin/pkgi-mysqltools rootpassword a13fz22"
+            echo "Error: missing parameter (root password)." >&2
+            echo "Example: bin/pkgi-mysqltools rootpassword a13fz22" >&2
             exit 1
         fi
         <?php echo getenv('APPNAME_HOME') ?>/etc/init.d/mysql stop > /dev/null
         if [ "$?" != "0" ]; then
-            echo "Root password cannot be changed because mysql server cannot be stopped..."
+            echo "Root password cannot be changed because mysql server cannot be stopped..." >&2
             exit 1
         fi
         ROOT_PASSWORD=$2
@@ -103,8 +122,8 @@ FLUSH PRIVILEGES;
 EOF
         $MYSQL_BOOTSTRAP <$tfile
         if [ "$?" != "0" ]; then
-            echo "Root password cannot be changed because mysql database has not been initialized."
-            echo "Please firstly initialize the mysql database: bin/pkgi-mysqltools init"
+            echo "Root password cannot be changed because mysql database has not been initialized." >&2
+            echo "Please firstly initialize the mysql database: bin/pkgi-mysqltools init" >&2
             rm -f $tfile
             exit 1
         else
@@ -115,8 +134,8 @@ EOF
 
     -mr | -makeroot | makeroot)
         if [ ${#} -lt 2 ] ; then
-            echo "Error: missing parameter (hostname)."
-            echo "Example: bin/mysqltools -mr gully.ads.intra.inist.fr"
+            echo "Error: missing parameter (hostname)." >&2
+            echo "Example: bin/mysqltools -mr gully.ads.intra.inist.fr" >&2
             exit 1
         fi
         MRHOST=${2}
@@ -180,14 +199,15 @@ EOF
         echo "usage: $0 ( query | dump | init | makeroot | copyto | copyfrom )"
     cat <<EOF
 
-   -q  | -query        - Permet de lancer la commande mysql (placez vos paramètres à la suite)
-   -i  | -init         - Initialisation de la base
-   -rp | -rootpassword - Réglage du mot de passe root (passé en paramètre)
-   -d  | -dump         - Permet de lancer la commande mysqldump (placez vos parametres à la suite)
-   -b  | -backup       - Équivalent de dump mais sans dumper les tables systèmes
-   -mr | -makeroot     - Permet de donner les droits de connexion à un hostname passé en paramètre
-   -t  | -copyto       - Copie d'une ou de toutes les bases sur un autre serveur 
-   -f  | -copyfrom     - Récupération d'une ou de toutes les bases venant d'un autre serveur
+   -q  | -query                           - Permet de lancer la commande mysql (placez vos paramètres à la suite)
+   -i  | -init                            - Initialisation de la base
+   -rp | -rootpassword                    - Réglage du mot de passe root (passé en paramètre)
+   -d  | -dump                            - Permet de lancer la commande mysqldump (placez vos parametres à la suite)
+   -b  | -backup                          - Équivalent de dump mais sans dumper les tables systèmes
+   -bc | -backup-cron [install|uninstall] - (Dés)installation d'un script de sauvegarde mysql quotidien en crontab
+   -mr | -makeroot                        - Permet de donner les droits de connexion à un hostname passé en paramètre
+   -t  | -copyto                          - Copie d'une ou de toutes les bases sur un autre serveur 
+   -f  | -copyfrom                        - Récupération d'une ou de toutes les bases venant d'un autre serveur
 
 EOF
         exit 1
