LSB compliance
git-svn-id: file:///root/pkgi/trunk@281 1d9e17c5-d814-4e76-8053-328317d3193c

diff --git a/sphinx/etc/init.d/searchd b/sphinx/etc/init.d/searchd
--- a/sphinx/etc/init.d/searchd
+++ b/sphinx/etc/init.d/searchd
@@ -1,206 +1,286 @@
 #!/bin/sh
 #!/bin/sh
+#
+# init.d script for Sphinx with LSB support.
+#
+# Please read this init.d carefully and modify the sections to
+# adjust it to the program you want to run.
+#
+# Copyright (c) 2010 Nicolas Thouvenin <nthouvenin@gmail.com>
+#
+# This is free software; you may redistribute it and/or modify
+# it under the terms of the GNU General Public License as
+# published by the Free Software Foundation; either version 2,
+# or (at your option) any later version.
+#
+# This is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License with
+# the Debian operating system, in /usr/share/common-licenses/GPL;  if
+# not, write to the Free Software Foundation, Inc., 59 Temple Place,
+# Suite 330, Boston, MA 02111-1307 USA
+#
 ### BEGIN INIT INFO
 # Provides:          searchd
-# Required-Start:    $remote_fs $network $syslog
-# Required-Stop:     $remote_fs $network $syslog
+# Required-Start:    $network $local_fs
+# Required-Stop:
+# Should-Start:      $named
+# Should-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Sphinx Search Engine Server 
+# Short-Description: Sphinx Search Engine
+# Description:       Sphinx
+#                    is 
+#                    search engine ...
 ### END INIT INFO
 
-# Specify path variable
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
-# Kill me on all errors
+DAEMON="<?php echo getenv('APPNAME_SPHINX_HOME') ?>/bin/searchd"
+NAME="searchd"
+DESC="Sphinx"
+LOGDIR=<?php echo getenv('APPNAME_HOME'); ?>/var/log/sphinx
+
+PIDFILE=<?php echo getenv('APPNAME_HOME'); ?>/var/run/$NAME/$NAME.pid
+
+test -x $DAEMON || exit 0
+
+. /lib/lsb/init-functions
+
+# Default options, these can be overriden by the information
+# at <?php echo getenv('APPNAME_HOME') ?>/etc/default/$NAME
+DAEMON_OPTS="-c <?php echo getenv('APPNAME_HOME') ?>/etc/sphinx/sphinx.conf"
+
+DIETIME=10              # Time to wait for the server to die, in seconds
+                        # If this value is set too low you might not
+                        # let some servers to die gracefully and
+                        # 'restart' will not work
+
+STARTTIME=2             # Time to wait for the server to start, in seconds
+                        # If this value is set each time the server is
+                        # started (on start or restart) the script will
+                        # stall to try to determine if it is running
+                        # If it is not set and the server takes time
+                        # to setup a pid file the log message might
+                        # be a false positive (says it did not start
+                        # when it actually did)
+
+LOGFILE=$LOGDIR/$NAME.log  # Server logfile
+#DAEMONUSER=<?php echo getenv('APPNAME_USER'); ?>
+                        # Users to run the daemons as. If this value
+                        # is set start-stop-daemon will chuid the server
+
+# Include defaults if available
+if [ -f <?php echo getenv('APPNAME_HOME') ?>/etc/default/$NAME ] ; then
+    . <?php echo getenv('APPNAME_HOME') ?>/etc/default/$NAME
+fi
+
+# Use this if you want the user to explicitly set 'RUN' in
+# <?php echo getenv('APPNAME_HOME') ?>/etc/default/
+if [ "x$RUN" != "xyes" ] ; then
+    log_failure_msg "$NAME disabled, please adjust the configuration to your needs "
+    log_failure_msg "and then set RUN to 'yes' in <?php echo getenv('APPNAME_HOME') ?>/etc/default/$NAME to enable it."
+    exit 1
+fi
+
+# Check that the user exists (if we set a user)
+# Does the user exist?
+if [ -n "$DAEMONUSER" ] ; then
+    if getent passwd | grep -q "^$DAEMONUSER:"; then
+        # Obtain the uid and gid
+        DAEMONUID=`getent passwd |grep "^$DAEMONUSER:" | awk -F : '{print $3}'`
+        DAEMONGID=`getent passwd |grep "^$DAEMONUSER:" | awk -F : '{print $4}'`
+    else
+        log_failure_msg "The user $DAEMONUSER, required to run $NAME does not exist."
+        exit 1
+    fi
+fi
+
+
 set -e
 
-# Set the paths to searchd as a variable so that someone who really
-# wants to can override the path in /etc/default/searchd.
-SEARCHD=<?php echo getenv('APPNAME_SPHINX_HOME') ?>/bin/searchd
-
-# Stop processing if searchd is not there
-[ -x $SEARCHD ] || exit 0
-
-# debconf may have this file descriptor open and it makes things work a bit
-# more reliably if we redirect it as a matter of course.  db_stop will take
-# care of this, but this won't hurt.
-exec 3>/dev/null
-
-# Source the init script configuration
-if [ -f "<?php echo getenv('APPNAME_HOME') ?>/etc/default/searchd" ]; then
-	. <?php echo getenv('APPNAME_HOME') ?>/etc/default/searchd
-fi
-
-# Load the pkgi profile
-test -f <?php echo getenv('APPNAME_HOME') ?>/etc/profile && . <?php echo getenv('APPNAME_HOME') ?>/etc/profile
-
-# Load the default location of the searchd config file
-if [ -z "$SEARCHD_CONF" ]; then
-	SEARCHD_CONF="<?php echo getenv('APPNAME_HOME') ?>/etc/sphinx/sphinx.conf"
-fi
-
-# Stop processing if the config file is not there
-if [ ! -r "$SEARCHD_CONF" ]; then
-  cat <<EOF >&2
-No configuration file was found for searchd at $SEARCHD_CONF.
-If you have moved the searchd configuration file please modify
-/etc/default/searchd to reflect this.  If you chose to not
-configure searchd during installation then you need to do so
-prior to attempting to start searchd.
-EOF
-  exit 0 # Should this be 1?
-fi
-
-# Find out the name of searchd's pid file
-if [ -z "$SEARCHD_PIDFILE" ]; then
-	if [ -f "$SEARCHD_CONF" ] ; then
-		SEARCHD_PIDFILE=`sed -ne 's/[[:space:]]\+pid_file[[:space:]]\+=[[:space:]]\+\(.\+\)/\1/p' \
-			"$SEARCHD_CONF"`
-		SEARCHD_OPTIONS="-c $SEARCHD_CONF $SEARCHD_OPTIONS"
-	fi
-fi
-
-# XXX: Breaks upgrading if there is no pidfile (invoke-rc.d stop will fail)
-# -- Torsten
-if [ -z "$SEARCHD_PIDFILE" ]; then
-	cat <<EOF >&2
-The pidfile for searchd is neither specified in "$SEARCHD_CONF".
-Consequently, searchd will not be started.
-EOF
-	exit 1
-fi
-
-# Make sure the pidfile directory exists with correct permissions
-piddir=`dirname "$SEARCHD_PIDFILE"`
-if [ ! -d "$piddir" ]; then
-	mkdir -p "$piddir"
-	[ -z "$SEARCHD_USER" ] || chown -R "$SEARCHD_USER" "$piddir"
-	[ -z "$SEARCHD_GROUP" ] || chgrp -R "$SEARCHD_GROUP" "$piddir"
-fi
-
-# Check whether we were configured to not start the services.
-check_for_no_start() {
-	if [ -n "$SEARCHD_NO_START" ]; then
-		echo 'Not starting searchd: SEARCHD_NO_START set in <?php echo getenv('APPNAME_HOME') ?>/etc/default/searchd' >&2
-		exit 0
-	fi
-	if [ -n "$SEARCHD_SENTINEL_FILE" ] && [ -e "$SEARCHD_SENTINEL_FILE" ]; then
-		echo "Not starting searchd: $SEARCHD_SENTINEL_FILE exists" >&2
-		exit 0
-	fi
-}
-
-# get the pid of searchd
-pidof_searchd_noexit() {
-    # if pidof is null for some reasons the script exits automagically
-    # classified as good/unknown feature
-    PIDS=`pidof searchd` || true
-
-    [ -e $SEARCHD_PIDFILE ] && PIDS2=`cat $SEARCHD_PIDFILE`
-    
-    # if there is a pid we need to verify that belongs to searchd
-    # for real
-    for i in $PIDS; do
-    	if [ "$i" = "$PIDS2" ]; then
-            # in this case the pid stored in the
-            # pidfile matches one of the pidof apache
-            # so a simple kill will make it
-            echo $i
-            return 0
-        fi
-    done
+running_pid() {
+# Check if a given process pid's cmdline matches a given name
+    pid=$1
+    name=$2
+    [ -z "$pid" ] && return 1
+    [ ! -d /proc/$pid ] &&  return 1
+    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
+    # Is this the expected server
+    [ "$cmd" != "$name" ] &&  return 1
     return 0
 }
 
+running() {
+# Check if the process is running looking at /proc
+# (works for all users)
 
-# Tell the user that something went wrong and give some hints for
-# resolving the problem.
-report_failure() {
-	if [ -n "$reason" ]; then
-		echo " - failed: "
-		echo "$reason"
-	else
-		echo " - failed."
-		cat <<EOF
-The operation failed but no output was produced. For hints on what went
-wrong please refer to the system's logfiles (e.g. /var/log/syslog).
-EOF
-
-		if [ -n "$SEARCHD_OPTIONS" ]; then
-			cat <<EOF
-
-Below, you can find the command line options used by this script to 
-run searchd. Do not forget to specify those options if you
-want to look to debugging output:
-  searchd $SEARCHD_OPTIONS
-EOF
-		fi
-	fi
+    # No pidfile, probably no daemon present
+    [ ! -f "$PIDFILE" ] && return 1
+    pid=`cat $PIDFILE`
+    running_pid $pid $DAEMON || return 1
+    return 0
 }
 
-# Start the searchd daemon and capture the error message if any to 
-# $reason.
-start_searchd() {
-	echo -n " searchd"
-	$SEARCHD $SEARCHD_OPTIONS >> $SEARCHD_LOG 2>&1 &
+start_server() {
+# Start the process using the wrapper
+        if [ -z "$DAEMONUSER" ] ; then
+            start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS >> $LOGFILE 2>&1
+            errcode=$?
+        else
+# if we are using a daemonuser then change the user id
+            start-stop-daemon --start --quiet --pidfile $PIDFILE \
+                        --chuid $DAEMONUSER \
+                        --exec $DAEMON -- $DAEMON_OPTS \
+						>> $LOGFILE 2>&1
+            errcode=$?
+        fi
+        return $errcode
 }
 
-# Stop the searchd daemon and capture the error message (if any) to
-# $reason.
-stop_searchd() {
-	echo -n " searchd"
-	reason="`start-stop-daemon --stop --quiet --oknodo --retry TERM/10 \
-		--pidfile "$SEARCHD_PIDFILE" \
-		--exec $SEARCHD 2>&1`"
+stop_server() {
+# Stop the process using the wrapper
+        if [ -z "$DAEMONUSER" ] ; then
+            killproc -p $PIDFILE $DAEMON >> $LOGFILE 2>&1
+            errcode=$?
+        else
+# if we are using a daemonuser then look for process that match
+            start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+                        --user $DAEMONUSER \
+                        --exec $DAEMON \
+                        >> $LOGFILE 2>&1
+            errcode=$?
+        fi
+
+        return $errcode
 }
 
-
-# Start the sphinx daemons
-start_sphinx() {
-	echo -n "Starting Sphinx:"
-	trap 'report_failure' 0
-	start_searchd
-	trap "-" 0
-        echo " (listening on <?php echo getenv('APPNAME_SPHINX_LISTEN_INTERFACE'); ?>:<?php echo getenv('APPNAME_SPHINX_LISTEN_PORT'); ?>)"
+reload_server() {
+    [ ! -f "$PIDFILE" ] && return 1
+    pid=`pidofproc -p $PIDFILE $DAEMON 2>/dev/null`
+    # Send a SIGUSR1
+    kill -s USR1 $pid  >/dev/null 2>&1
+    return $?
 }
 
-# Stop the sphinx daemons
-stop_sphinx() {
-	echo -n "Stopping Sphinx:"
-	trap 'report_failure' 0
-	stop_searchd
-	trap "-" 0
-	echo .
+force_stop() {
+# Force the process to die killing it manually
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+        # Is it really dead?
+        sleep "$DIETIME"s
+        if running ; then
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
+        fi
+    fi
+    rm -f $PIDFILE
 }
 
-# Check if sphinx is running
-status_sphinx() {
-	PID=$(pidof_searchd_noexit)
-	if [ -n "$PID" ]; then
-		echo "Sphinx is running (pid $PID, listening on <?php echo getenv('APPNAME_SPHINX_LISTEN_INTERFACE')?>:<?php echo getenv('APPNAME_SPHINX_LISTEN_PORT')?>)."
-		exit 0
-	else
-		echo "Sphinx is not running."
-		exit 1
-	fi
-}
 
 case "$1" in
   start)
-	check_for_no_start
-  	start_sphinx ;;
+        log_daemon_msg "Starting $DESC " "$NAME"
+        # Check if it's running first
+        if running ;  then
+            log_progress_msg "apparently already running"
+            log_end_msg 0
+            exit 0
+        fi
+        if start_server ; then
+            # NOTE: Some servers might die some time after they start,
+            # this code will detect this issue if STARTTIME is set
+            # to a reasonable value
+            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
+            if  running ;  then
+                # It's ok, the server started and is running
+                log_end_msg 0
+            else
+                # It is not running after we did start
+                log_end_msg 1
+            fi
+        else
+            # Either we could not start it
+            log_end_msg 1
+        fi
+        ;;
   stop)
-  	stop_sphinx ;;
+        log_daemon_msg "Stopping $DESC" "$NAME"
+        if running ; then
+            # Only stop the server if we see it running
+            errcode=0
+            stop_server || errcode=$?
+            log_end_msg $errcode
+        else
+            # If it's not running don't do anything
+            log_progress_msg "apparently not running"
+            log_end_msg 0
+            exit 0
+        fi
+        ;;
+  force-stop)
+        # First try to stop gracefully the program
+        $0 stop
+        if running; then
+            # If it's still running try to kill it more forcefully
+            log_daemon_msg "Stopping (force) $DESC" "$NAME"
+            errcode=0
+            force_stop || errcode=$?
+            log_end_msg $errcode
+        fi
+        ;;
   restart|force-reload)
-	check_for_no_start
-  	stop_sphinx
-	start_sphinx
-	;;
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        errcode=0
+        stop_server || errcode=$?
+        # Wait some sensible amount, some server need this
+        [ -n "$DIETIME" ] && sleep $DIETIME
+        start_server || errcode=$?
+        [ -n "$STARTTIME" ] && sleep $STARTTIME
+        running || errcode=$?
+        log_end_msg $errcode
+        ;;
   status)
-  	status_sphinx ;;
+
+        log_daemon_msg "Checking status of $DESC" "$NAME"
+        if running ;  then
+            log_progress_msg "running"
+            log_end_msg 0
+        else
+            log_progress_msg "apparently not running"
+            log_end_msg 1
+            exit 1
+        fi
+        ;;
+  reload)
+		# log_daemon_msg "Reloading $DESC configuration files" "$NAME"
+        if running ; then
+			reload_server
+			if ! running ;  then
+				# Process died after we tried to reload
+				log_progress_msg "died on reload"
+				log_end_msg 1
+				exit 1
+			fi
+		else
+			log_progress_msg "server is not running"
+			log_end_msg 1
+			exit 1
+		fi
+		;;
   *)
-  	echo "Usage: $0 {start|stop|restart|status}"
-	exit 1
-	;;
+        N=<?php echo getenv('APPNAME_HOME'); ?>/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
+
+exit 0
